[TOC]
## 1. Promise 含义 ##

Promise 是异步编程的一种解决方案

`Promise`对象有以下两个特点。

（1）Promise`对象代表一个异步操作，有三种状态：`**pending`（进行中）、`fulfilled`（已成功）和`rejected`（已失败）**。只有异步操作的结果，可以决定当前是哪一种状态，

（2）Promise`对象的状态改变，只有两种可能：**从`pending`变为`fulfilled`和从`pending`变为`rejected`。**

## 2. 错误处理相关 ##

(1) 如果 Promise 状态已经变成resolved，再抛出错误是无效的，并且不会执行后面的代码

```js
const promise = new Promise(function(resolve, reject) {
  resolve('ok');
  throw new Error('test');
  console.log("1");
});
promise
  .then(function(value) { console.log(value) })
  .catch(function(error) { console.log(error) });
// ok
```

(2) Promise 指定在下一轮“事件循环”再抛出错误。到了那个时候，Promise 的运行已经结束了，所以这个错误是在 Promise 函数体外抛出的，会冒泡到最外层，成了未捕获的错误。和上面的不一样可比较

```js
const promise = new Promise(function (resolve, reject) {
  resolve('ok');
  setTimeout(function () { throw new Error('test') }, 0)
});
promise.then(function (value) { console.log(value) });
// ok
// Uncaught Error: test
```

(3) node

Node 有一个`unhandledRejection`事件，专门监听未捕获的`reject`错误，上面的脚本会触发这个事件的监听函数，可以在监听函数里面抛出错误。

```javascript
process.on('unhandledRejection', function (err, p) {
  throw err;
});
```

## 3. Promise.all()  ##

> `Promise.all`方法的参数可以不是数组，但必须具有 Iterator 接口，且返回的每个成员都是 Promise 实例。

`Promise.all`方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。

```javascript
const p = Promise.all([p1, p2, p3]);
```

`**p`的状态由`p1`、`p2`、`p3`决定，分成两种情况。**

（1）只有`p1`、`p2`、`p3`的状态都变成`fulfilled`，`p`的状态才会变成`fulfilled`，此时`p1`、`p2`、`p3`的返回值组成一个数组，传递给`p`的回调函数。

（2）只要`p1`、`p2`、`p3`之中有一个被`rejected`，`p`的状态就变成`rejected`，此时第一个被`reject`的实例的返回值，会传递给`p`的回调函数。

## 4. Promise.resolve() ##

由于字符串Hello不属于异步操作（判断方法是字符串对象不具有 then 方法），返回 Promise 实例的状态从一生成就是resolved，所以回调函数会立即执行。Promise.resolve方法的参数，会同时传给回调函数。

Promise.resolve()在本轮“事件循环”结束时执行，

```js
setTimeout(function () {
  console.log('three');
}, 0);

Promise.resolve().then(function () {
  console.log('two');
});

console.log('one');

// one
// two
// three
```
## 5. Generator 函数与 Promise 的结合 ##

```javascript
function getFoo () {
  return new Promise(function (resolve, reject){
    resolve('foo');
  });
}

const g = function* () {
  try {
    const foo = yield getFoo();
    console.log(foo);
  } catch (e) {
    console.log(e);
  }
};

function run (generator) {
  const it = generator();

  function go(result) {
    if (result.done) return result.value;

    return result.value.then(function (value) {
      return go(it.next(value));
    }, function (error) {
      return go(it.throw(error));
    });
  }

  go(it.next());
}

run(g);
```

## 6. Promise.try() ##

***使用场景***

不知道或者不想区分，函数`f`是同步函数还是异步操作，但是想用 Promise 来处理它。因为这样就可以不管`f`是否包含异步操作，都用`then`方法指定下一步流程，用`catch`方法处理`f`抛出的错误。

```js
// 如果f是同步函数，那么它会在本轮事件循环的末尾执行。
Promise.resolve().then(f)

// 同步函数同步执行，异步函数异步执行
// 第一种
const f = () => console.log('now');
(async () => f())();
console.log('next');
// now
// next

// 第二种 就是 Promise.try 的原理
const f = () => console.log('now');
(
  () => new Promise(
    resolve => resolve(f())
  )
)();
console.log('next');
// now
// next

```

***使用***

```javascript
Promise.try(() => database.users.get({id: userId}))
  .then(...)
  .catch(...)
```

